package com.example.lrb.enums;

/**
 * @date 2022-03-20 22:22d
 */
public enum NodeEnums {
    REQUIRE_CERTIFICATION, WAITING_CERTIFICATION, AUTHORIZED, UNAUTHORIZED, DEFEAT_CERTIFICATION,
    WAITING_AUDIT, AUDIT_PASS, AUDIT_NO_PASS
}
